### ISSUE TITLE
Flytte fra internal til public repo

### ISSUE THREAD

**Issue by MikAoJk** [navikt/familie-prosessering#135]
Hei!
Lurte på om det var noe spesiell grunn til at repoet er internal.
https://github.com/navikt/offentlig
@navikt/teamfamilie

**Comment by charliemidtlyng** [comment]
Etter å ha saumfart kode og innhold så ser vi ingen grunn til at denne skal være internal (er en internapp, men koden er ikke farlig). 
Takk for heads up, @MikAoJk !
